name: PR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Caching Requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

        # uses: actions/cache@v3
        # with:
        #   path: ~/.cache/pip
        #   key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ github.run_id }}
        #   restore-keys: ${{ runner.os }}-pip-

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: main
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.18
          run: 
            
      - name: Run tests
        run: pytest
