name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: caching-requirements
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: Linux-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: Linux-pip-

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: main
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.18
            
      - name: Run tests
        run: pytest
