name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout
        with:
          submodules: 'recursive'
          ref: v2
          
      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: 3.9.1
            
      - name: Run tests
        run: pytest
