name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: main
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.18
            
      - name: Run tests
        run: pytest
